# home/modules/attract-mode/render.nix
#
# Pure formatters for attract-mode's two config file formats. Kept separate
# from the module so they can be evaluated and checked without instantiating
# home-manager.
#
# Widths replicate attract-mode's own writers (src/fe_info.cpp,
# src/fe_input.cpp): std::setw is a MINIMUM, so a key longer than the width is
# emitted unpadded and still gets its single trailing space. The parser treats
# space and tab interchangeably, so these widths are cosmetic — matched only so
# a Nix-written file diffs cleanly against an attract-mode-written one.
{lib}: rec {
  header = "# Generated by home-manager. Do not edit — changes will be overwritten.";

  # Right-pad `s` to at least `w` characters.
  pad = w: s: s + lib.strings.replicate (lib.max 0 (w - lib.stringLength s)) " ";

  # attract.cfg key line. depth 1 = "\t", depth 2 = "\t\t".
  cfgLine = depth: key: value:
    lib.strings.replicate depth "\t" + pad 20 key + " " + value;

  # attract.cfg section. `name` is appended to the header after a TAB when set
  # (e.g. `display` + TAB + `MAME`); headers like `general` have no name.
  # `pairs` is a LIST of {name, value} — attract-mode allows repeated keys
  # (input_map maps one action to several inputs), which an attrset cannot hold.
  cfgSection = {
    header,
    name ? null,
    pairs,
  }:
    (
      if name == null
      then header
      else header + "\t" + name
    )
    + "\n"
    + lib.concatMapStrings (p: cfgLine (p.depth or 1) p.name p.value + "\n") pairs;

  # emulators/<name>.cfg key line — no leading indent.
  emuLine = key: value: pad 20 key + " " + value;

  # emulators/<name>.cfg artwork line: different widths from emuLine.
  emuArtworkLine = slot: path: pad 10 "artwork" + " " + pad 15 slot + " " + path;
}
