name: "auto-deploy: build & publish"

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-hosts.yml
    with:
      publish-pages: true
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
